from __future__ import annotations

from pathlib import Path
from typing import Any

import nbformat
from nbformat import NotebookNode

from src.artifact_store import utc_timestamp_string
from src.schemas import LearnerProfile, ModelProvenance, NotebookBatch, NotebookPlan, ParsedPaper


def load_notebook_batches(batch_paths: list[Path]) -> list[NotebookBatch]:
    """Load persisted section batches from disk without changing their order."""

    loaded_notebook_batches: list[NotebookBatch] = []
    for batch_path in batch_paths:
        loaded_notebook_batches.append(NotebookBatch.model_validate_json(batch_path.read_text(encoding="utf-8")))
    return loaded_notebook_batches


def build_notebook_metadata(
    notebook_plan: NotebookPlan,
    run_id: str,
    code_version: str,
    model_provenance: ModelProvenance | None,
    generated_section_batches: list[NotebookBatch],
    parsed_paper: ParsedPaper | None = None,
) -> dict[str, Any]:
    """Build notebook-level provenance metadata from existing stage artifacts."""

    chunk_provenance_by_section: dict[str, dict[str, Any]] = {}
    for generated_section_batch in generated_section_batches:
        aggregated_source_chunk_ids: list[str] = []
        seen_chunk_ids: set[str] = set()
        for notebook_cell in generated_section_batch.cells:
            for source_chunk_id in notebook_cell.source_chunk_ids or []:
                if source_chunk_id in seen_chunk_ids:
                    continue
                seen_chunk_ids.add(source_chunk_id)
                aggregated_source_chunk_ids.append(source_chunk_id)

        chunk_provenance_by_section[generated_section_batch.section_id] = {
            "section_title": generated_section_batch.section_title,
            "chunk_ids": aggregated_source_chunk_ids,
        }

    return {
        "authors": [{"name": "paper-to-notebook"}],
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.11",
        },
        "paper_to_notebook": {
            "source_paper_title": parsed_paper.paper_title if parsed_paper is not None else notebook_plan.paper_id,
            "paper_id": notebook_plan.paper_id,
            "run_id": run_id,
            "model_name": model_provenance.model_name if model_provenance is not None else None,
            "inference_backend": model_provenance.inference_backend if model_provenance is not None else None,
            "generation_timestamp_utc": utc_timestamp_string(),
            "project_version_or_code_version": code_version,
            "pedagogical_depth": notebook_plan.learner_profile.preferred_depth,
            "chunk_provenance_by_section": chunk_provenance_by_section,
        },
    }


def build_notebook_object(
    notebook_title: str,
    learner_profile: LearnerProfile,
    generated_section_batches: list[NotebookBatch],
    notebook_metadata: dict[str, Any],
) -> NotebookNode:
    """Build a notebook object through nbformat helpers."""

    notebook_object = nbformat.v4.new_notebook()
    notebook_object.metadata.update(notebook_metadata)

    overview_cell = nbformat.v4.new_markdown_cell(
        source=_build_overview_markdown(notebook_title=notebook_title, learner_profile=learner_profile)
    )
    notebook_cells: list[NotebookNode] = [overview_cell]

    for generated_section_batch in generated_section_batches:
        for notebook_cell_spec in generated_section_batch.cells:
            if notebook_cell_spec.cell_type == "markdown":
                notebook_cells.append(
                    nbformat.v4.new_markdown_cell(
                        source=notebook_cell_spec.source,
                        metadata=dict(notebook_cell_spec.metadata),
                    )
                )
                continue

            notebook_cells.append(
                nbformat.v4.new_code_cell(
                    source=notebook_cell_spec.source,
                    metadata=dict(notebook_cell_spec.metadata),
                    execution_count=None,
                    outputs=[],
                )
            )

    notebook_object.cells = notebook_cells
    return notebook_object


def write_notebook(notebook_object: NotebookNode, output_path: str | Path) -> Path:
    notebook_output_path = Path(output_path)
    notebook_output_path.parent.mkdir(parents=True, exist_ok=True)
    with notebook_output_path.open("w", encoding="utf-8") as output_file:
        nbformat.write(notebook_object, output_file)
    return notebook_output_path


def _build_overview_markdown(notebook_title: str, learner_profile: LearnerProfile) -> str:
    return "\n".join(
        [
            f"# {notebook_title}",
            "",
            "This notebook was generated by the staged `paper-to-notebook` pipeline.",
            "",
            f"**Pedagogical depth**: {learner_profile.preferred_depth}",
            f"**Pacing**: {learner_profile.preferred_pacing}",
            f"**Math background**: {learner_profile.mathematics_background}",
            f"**Machine learning background**: {learner_profile.machine_learning_background}",
            f"**Deep learning background**: {learner_profile.deep_learning_background}",
            f"**Python background**: {learner_profile.python_background}",
            f"**Tensor familiarity**: {learner_profile.tensor_familiarity}",
        ]
    )

